export default {
  GREY_LIGHTEST: "#CFCFCF",
  GREY_LIGHT: "#BEBEBE",
  GREY: "#ACACAC",
  GREY_DARK: "#9B9B9B",
  GREY_DARKEST: "#898989",

  RED: "#EF919B",
  ORANGE: "#F8B392",
  YELLOW: "#F6F7B0",
  GREEN: "#A0CFA2",
  BLUE: "#71BEE7",
};
