edition = "2021"
fn_params_layout = "Vertical"
imports_granularity = "Crate"
normalize_comments = true
unstable_features = true
use_field_init_shorthand = true
use_try_shorthand = true
wrap_comments = true
